# Generated by Django 4.2.3 on 2023-07-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(max_length=10)),
                ('long', models.DecimalField(decimal_places=20, max_digits=25)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=25)),
                ('ts', models.DateTimeField()),
                ('sts', models.DateTimeField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
