# Generated by Django 4.2.3 on 2023-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocation',
            name='device_id',
            field=models.IntegerField(),
        ),
    ]
